services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: pos_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:your_password@db:5432/pos_dev_db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  postgres_data:
