version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pos_backend_user
      POSTGRES_PASSWORD: pos_backend_password
      POSTGRES_DB: pos_backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://pos_backend_user:pos_backend_password@db:5432/pos_backend_db
      POS_BACKEND_SECRET_KEY: your_secret_key
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
