"""Add role column to users

Revision ID: c9deed68d13b
Revises: 
Create Date: 2024-10-24 10:00:17.424970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9deed68d13b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_table('roles')
    #op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'password')
    op.drop_column('users', 'id_user')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id_user', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id_role'])
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'role')
    op.drop_column('users', 'id')
    op.create_table('roles',
    sa.Column('id_role', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_role', name='roles_pkey')
    )
    # ### end Alembic commands ###
